steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "europe-west3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}-backend:${COMMIT_SHA}",
        "-f",
        "./backend/Dockerfile",
        ".",
      ]
    id: Build-backend
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "europe-west3-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}-frontend:${COMMIT_SHA}",
        "-f",
        "./frontend/Dockerfile",
        ".",
      ]
    id: Build-frontend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-backend:$COMMIT_SHA
    id: Push-backend
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-frontend:$COMMIT_SHA
    id: Push-frontend
  - name: "docker/compose:2.21.0"
    args: ["up", "-d"]
    id: compose
images:
  [
    "${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}",
  ]
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: quivr-all
  _DEPLOY_REGION: europe-west3
  _AR_HOSTNAME: europe-west3-docker.pkg.dev
  _TRIGGER_ID: 5b501942-5df8-4ac5-b369-fe370736cb64
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - quivr-all
