version: "3"

services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    ports:
      - 3000:3000
  backend-core:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend-core
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-chat:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend-chat
    command: uvicorn --reload chat_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-crawl:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend-crawl
    command: uvicorn --reload crawl_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-upload:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend-upload
    command: uvicorn --reload upload_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/
