version: "3"

services:
  # frontend:
  #   env_file:
  #     - ./frontend/.env
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   container_name: web
  #   restart: always
  #   ports:
  #     - 8080:8080
  backend-core:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-core
    command: uvicorn main:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-chat:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-chat
    command: uvicorn chat_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-crawl:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-crawl
    command: uvicorn crawl_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/

  backend-upload:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-upload
    command: uvicorn upload_service:app --host 0.0.0.0 --port 5050
    restart: always
    volumes:
      - ./backend/:/code/
